# Generated by Django 4.1.7 on 2023-03-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='gsheetId',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
