# Generated by Django 4.1.7 on 2023-03-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_layout_gsheetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='gsheetId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
