# Generated by Django 4.1.7 on 2023-03-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_alter_layout_gsheetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
