# Generated by Django 4.1.7 on 2023-03-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0004_layout_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='train',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
